---
# Runs only on COMPOSE
- hosts: compose
  become: true
  gather_facts: false
  tasks:
  - name: install docker prereq
    apt:
      name:
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
#  - name: add elastek repo
#    script: ./task_elastic.sh
  - name: Install packages only on compose server
    apt:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-compose-plugin
        - ntp
      state: present
  - name: start and enable ntpd service
    service:
      name: ntp
      state: started
      enabled: yes
      #  - name: configure logging via script
      #    script: ./task_log.sh
