---
# Runs only on COMPOSE
- hosts: compose
  become: true
  gather_facts: false
  roles:
    - node_exporter
  tasks:
  - name: install Docker Repo
    shell: "{{ item }}"
    loop:
      - " sudo mkdir -p /etc/apt/keyrings"
      - " curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg"
      - ' echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null'
  - name: Pause for 10 seconds to wait for apt
    ansible.builtin.pause:
      seconds: 10
  - name: update apt list
    apt:
      update_cache: yes    
  - name: install docker prereq packages
    apt:
      name:
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
  - name: Install Docker packages on compose server
    apt:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-compose-plugin
        - ntp
        - docker-compose
      state: present
  - name: start and enable ntpd service
    service:
      name: ntp
      state: started
      enabled: yes
  - name: Avoid hanging when http(s) password is missing
    ansible.builtin.git:
      repo: https://github.com/NickVG/astraTask.git
      dest: /vagrant
  - name: Pause for 10 seconds to wait for docker
    ansible.builtin.pause:
      seconds: 10
  - name: start docker-compose
    script: "./compose/docker-compose.sh"
  - name: Allow port 3000
    ufw:
      rule: allow
      port: 3000
