# prometheus.yml
#

global:
  scrape_interval: 15s

scrape_configs:
- job_name: ubuntuNode
  static_configs:
#  - targets: ['192.168.43.180:9100']
  - targets: ['192.168.56.102:9100']

#remote_write:
#  - url: "<Your Prometheus remote_write endpoint>"
#    basic_auth:
#      username: "<Your Grafana Username>"
#      password: "<Your Grafana API key>"

#global:
#    scrape_interval: 5s
#    external_labels:
#        monitor: 'my-monitor'
#scrape_configs:
#    - job_name: 'prometheus'
#      target_groups:
#          - targets: ['192.168.43.180:9090']
#    - job_name: 'node-exporter'
#      target_groups:
#          - targets: ['192.168.43.180:9100']

#global:
#    scrape_interval: 5s
#    external_labels:
#        monitor: 'my-monitor'
#scrape_configs:
#    - job_name: 'prometheus'
#      target_groups:
#          - targets: ['192.168.43.180:9100']
#    - job_name: 'ubuntu'
#      target_groups:
      #  static_configs:
#          - targets: ['192.168.43.180:9100']
